### ISSUE TITLE
Missing / in  task: find role directory  (awx aware)

### ISSUE THREAD

**Issue by riwar** [joe-speedboat/ansible.mariadb#1]
Hi!

There seams to be a missing / between roles and {{role_path...}}/tasks

- name: find role directory  (awx aware)
  find:
    paths: 
   ... 
    - "{{ lookup('env', 'HOME') }}/.ansible/roles{{role_path|basename}}/tasks" 

Should be:

- name: find role directory  (awx aware)
  find:
    paths: 
   ... 
    - "{{ lookup('env', 'HOME') }}/.ansible/roles/{{role_path|basename}}/tasks"

**Comment by joe-speedboat** [comment]
thanks, its in now!
